spring.application.name=BankOne

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bankone
spring.datasource.username=bankone_user
spring.datasource.password=BankOne@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Execute schema.sql and data.sql
spring.sql.init.mode=always

# Run schema.sql before Hibernate (recommended with ddl-auto=update)
spring.jpa.defer-datasource-initialization=false

# Server
server.port=8080


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
jwt.secret=ReplaceThisWithAVeryLongRandomSecretKeyAtLeast32CharactersLong
jwt.expiration=3600000

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG