# Activate with: SPRING_PROFILES_ACTIVE=prod
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
